### PR TITLE
Add hostname detection and fix minor spelling issues in comments

### PR DESCRIPTION
**Pull request by tripleab**

### CODE REVIEW

**Comment by KyraTheDonkey** [comment]
I'm not yet sure what to do about it in code, I need to research that, but I will warn you that not every install has the `hostname` command. See my system:
image

**Comment by tripleab** [comment]
Ok, thanks for letting me know. There is a $HOST environment variable (at least on my system) so that could be read as a fallback?

**Comment by tripleab** [comment]
> Ok, thanks for letting me know. There is a $HOST environment variable (at least on my system) so that could be read as a fallback?

I've now added functionality to read `/proc/sys/kernel/hostname` if the `hostname` command isn't found

**Comment by KyraTheDonkey** [comment]
> Ok, thanks for letting me know. There is a $HOST environment variable (at least on my system) so that could be read as a fallback?

Bash has $HOSTNAME, and not $HOST, so that wouldn't work either.

> I've now added functionality to read /proc/sys/kernel/hostname if the hostname command isn't found

That does work for me now.

I alternatively got `uname -n` working on my side. Not sure how many failsafes are needed, but I'm guessing there's a lot of branching for all the possible distros and setups.

**Comment by tripleab** [comment]
> Bash has $HOSTNAME, and not $HOST, so that wouldn't work either.

I'm used to ZSH which uses $HOST, so that's where the mistake came haha

I think reading from /proc should be fairly universal, but I could also add uname -n

**Comment by bdejean** [comment]
> I alternatively got `uname -n` working on my side. Not sure how many failsafes are needed, but I'm guessing there's a lot of branching for all the possible distros and setups.

Hi, yes that may be preferable to cycle through `uname -n` and `hostname` instead of doing some os-specific checks.

**Comment by tripleab** [comment]
> Hi, yes that may be preferable to cycle through `uname -n` and `hostname` instead of doing some os-specific checks.

Done! Thanks for the advice

**Comment by Ruturajn** [comment]
Hi,
Thanks for the PR. Although I merged [this PR](https://github.com/Ruturajn/fetchit/pull/5), before, the one you have opened, which has created conflicts in `src/main.rs` (as you can probably see). So, should I make the edits, to resolve the conflicts, or do you want to create a New PR? Please let me know.
Thanks

**Comment by tripleab** [comment]
Hi
I have resolved the conflicts, and everything seems to be working for me
Thanks!

**Comment by Ruturajn** [comment]
Hi,
Thanks for resolving the conflicts. I also had another question, what is the `.idea` entry in the `gitignore` file?

Thanks

**Comment by Ruturajn** [comment]
Apart from that, I think that it's ready to merge 😄.

EDIT: I really like the glyph for the `hostname`. Thanks.

**Comment by tripleab** [comment]
Happy to help out! 😃 I was worried about my glyph selection so I'm glad you like it!

> Thanks for resolving the conflicts. I also had another question, what is the `.idea` entry in the `gitignore` file?

`.idea` [contains configuration for the Intellij IDE](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-), which gets auto-generated whenever a project is opened in it. Some of the contents can be useful and JetBrains recommend keeping parts in version control in some situations, however in projects where many people use different editors, it's probably best not to rely on editor specific configuration

**Comment by Ruturajn** [comment]
Ohh, Ok. Thanks. I am merging this now.

**Pull request merged**
