### PR TITLE
refactor: remove match arm

### PR DESCRIPTION
**Pull request by mainrs**
`.or_else` gets called if the value of the `Result` is `Err`. At the end we call `unwrap_or_else` which either uses the value in if it is `Ok` (i.e., some package manager has been found) or it uses "Unknown".

### CODE REVIEW

**Comment by mainrs** [comment]
Ah, let me remove the clippy warnings commit ups

**Comment by mainrs** [comment]
I changed `packages_generic` to receive a `&[&str]` instead of `Vec<&str>`. `&[&str]` is called a slice and does not allocate memory on the heap. `Vec<&str>` does allocate memory on the heap, or rather the instantiation of a vector using `vec![]` does.

**Comment by Ruturajn** [comment]
Ohh, I thought using `Vec<&str>` was the way to go, for avoiding memory allocating in the heap. Thanks and the `match` arm
was a huge pain, even while writing it. I just did not know an alternative way to do it.

**Comment by mainrs** [comment]
> Ohh, I thought using Vec<&str> was the way to go, for avoiding memory allocating in the heap.

Maybe you confused `String` with `&str` and thought that since `Vec<&str>` is a reference to a string it does not allocate. But you store it in a dynamic data structure, thus it has to live in the heap.

**Comment by Ruturajn** [comment]
Also, I have made an error, [here](https://github.com/Ruturajn/fetchit/blob/01986eff44bb4574d552e80944a2ae955ec18512/src/lib.rs#L19), so I will need to correct that. Maybe, doing that will cause conflicts with the stuff you have already changed. Do you have any suggestions, regarding this?
Thanks

**Comment by mainrs** [comment]
Two options:

1) Merge and fix the error after that.
2) Fix the error first. In that case this PR would have to be re-based. That means getting it up-to-date with the newest code in the main branch. If conflicts arise, git shows them and soneone has to fix them manually. Once that is done, the commit with the fixes gets pushed to this branch and the PR can be merged without conflicts. If not conflicts arise, the PR can be merged as-is.

It is up to you .

**Comment by Ruturajn** [comment]
I think I will go with the first option since I am not very experienced in handling git conflicts.
Thanks

**Comment by Ruturajn** [comment]
Hey, could you also add yourself as the author, in the source files?
Thanks

**Pull request merged**
